name: Flutter iOS Basic Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  FLUTTER_VERSION: "3.24.5"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Analyze code
        run: flutter analyze

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS app (Debug)
        run: |
          flutter build ios --debug --no-codesign
        env:
          FLUTTER_BUILD_NUMBER: ${{ github.run_number }}

      - name: Build iOS app (Release)
        run: |
          flutter build ios --release --no-codesign
        env:
          FLUTTER_BUILD_NUMBER: ${{ github.run_number }}

      - name: Upload debug build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-build
          path: build/ios/iphoneos/Runner.app
          retention-days: 7

      - name: Upload release build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-build
          path: build/ios/iphoneos/Runner.app
          retention-days: 7

  build-ios-simulator:
    name: Build iOS Simulator
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS Simulator app
        run: |
          flutter build ios --debug --simulator
        env:
          FLUTTER_BUILD_NUMBER: ${{ github.run_number }}

      - name: Upload simulator build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-build
          path: build/ios/iphonesimulator/Runner.app
          retention-days: 7

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [build-ios, build-ios-simulator]
    if: always()
    steps:
      - name: Notify on success
        if: needs.build-ios.result == 'success' && needs.build-ios-simulator.result == 'success'
        run: |
          echo "✅ iOS builds completed successfully!"
          
      - name: Notify on failure
        if: needs.build-ios.result == 'failure' || needs.build-ios-simulator.result == 'failure'
        run: |
          echo "❌ iOS build failed!"
          exit 1 